# Frontend Production Environment Values

replicaCount: 5

image:
  repository: <ECR_REGISTRY>/servicepro-frontend # Replace with your ECR registry
  tag: '' # Set by CI/CD based on git tag
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
  hosts:
    - host: servicepro.com
      paths:
        - path: /
          pathType: Prefix
    - host: www.servicepro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-prod-tls
      hosts:
        - servicepro.com
        - www.servicepro.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

config:
  apiUrl: 'https://api.servicepro.com'
  wsUrl: 'wss://api.servicepro.com/ws'
  environment: production
  enableAnalytics: true
  enableDebug: false

# Production pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 3
