version: '2'

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - bodyclose
    - unconvert
    - misspell

  settings:
    govet:
      disable:
        - printf
        - copylocks

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/javaknight1/servicepro

output:
  formats:
    colored-line-number: {}
