apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicepro-frontend.fullname" . }}
  labels:
    {{- include "servicepro-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "servicepro-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "servicepro-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "servicepro-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-frontend.fullname" . }}
              key: apiUrl
        - name: VITE_WS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-frontend.fullname" . }}
              key: wsUrl
        - name: VITE_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-frontend.fullname" . }}
              key: environment
        - name: VITE_ENABLE_ANALYTICS
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-frontend.fullname" . }}
              key: enableAnalytics
        - name: VITE_ENABLE_DEBUG
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-frontend.fullname" . }}
              key: enableDebug
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
