export {
  initErrorTracking,
  captureException,
  captureMessage,
  setUser,
  setTag,
  setExtra,
  addBreadcrumb,
  startPerformanceSpan,
  getActiveSpan,
  flush,
  close,
  Sentry,
  type ErrorTrackingConfig,
} from './sentry';
