apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicepro-backend.fullname" . }}
  labels:
    {{- include "servicepro-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "servicepro-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "servicepro-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "servicepro-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        env:
        - name: PORT
          value: {{ .Values.config.port | quote }}
        - name: ENV
          value: {{ .Values.config.environment | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        - name: CORS_ALLOWED_ORIGINS
          value: {{ .Values.config.corsAllowedOrigins | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: databaseUrl
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)/$(REDIS_DB)"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: redisHost
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: redisPort
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: redisDb
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: redisPassword
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: jwtSecret
        - name: JWT_EXPIRATION
          value: {{ .Values.jwt.expiration | quote }}
        - name: AWS_REGION
          value: {{ .Values.aws.region | quote }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: awsAccessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "servicepro-backend.fullname" . }}
              key: awsSecretAccessKey
        - name: S3_BUCKET_NAME
          value: {{ .Values.aws.s3Bucket | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
